# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df6765364123fce2a39aeb27b9be107b535ae08fb90bce5d5bc73b92aadd810bd8d65df481bfbeff7bed931e6b20bc1ae9458dfef3c47779c0c6cdb8a033006

test:
  secret_key_base: a44ee541d6d295187cc89276de814ee116671069c29a5374cfb32b9cade09f16f7a26bb84bb422a26c5f8736fc46f139e2e196647bf1153aa220e46238845c12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
